CREATE TABLE [dbo].[MembersOfParliament] (
    [ID]                 INT            IDENTITY (1, 1) NOT NULL,
    [Title]              NVARCHAR (220) NULL,
    [Forenames]          NVARCHAR (50)  NOT NULL,
    [Surname]            NVARCHAR (50)  NOT NULL,
    [FromDate]           DATETIME       NOT NULL,
    [ToDate]             DATETIME       NULL,
    [Email Address]      NVARCHAR (100) NULL,
    [Mobile]             NVARCHAR (20)  NULL,
    [GovernmentPosition] NVARCHAR (150) NULL,
    [Notes]              NVARCHAR (MAX) NULL,
    [StatusID]           INT            CONSTRAINT [DF_MembersOfParliament_Status] DEFAULT (N'Active') NULL,
    [RoleID]             INT            CONSTRAINT [DF_MembersOfParliament_Role] DEFAULT (N'Backbencher') NULL,
    [ConstituencyID]     INT            NULL,
    [PartyID]            INT            NOT NULL,
    [MemberID]           NVARCHAR (10)  NULL,
    [DodsID]             NVARCHAR (10)  NULL,
    [PimsID]             NVARCHAR (10)  NULL,
    [CreatedBy]          INT            NOT NULL,
    [CreatedDate]        DATETIME       NOT NULL,
    [LastChangedBy]      INT            NOT NULL,
    [LastChangedDate]    DATETIME       NOT NULL,
    CONSTRAINT [PK_MembersOfParliament] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MembersOfParliament_MPRole_RoleID] FOREIGN KEY ([RoleID]) REFERENCES [dbo].[MPRole] ([ID]),
    CONSTRAINT [FK_MembersOfParliament_Constituency_ConstituencyID] FOREIGN KEY ([ConstituencyID]) REFERENCES [dbo].[Constituency] ([ID]),
    CONSTRAINT [FK_MembersOfParliament_Party_PartyID] FOREIGN KEY ([PartyID]) REFERENCES [dbo].[Party] ([ID]),
    CONSTRAINT [FK_MembersOfParliament_MPStatus_StatusID] FOREIGN KEY ([StatusID]) REFERENCES [dbo].[MPStatus] ([ID]),
    CONSTRAINT [FK_MembersOfParliament_User_CreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_MembersOfParliament_User_LastChangedBy] FOREIGN KEY ([LastChangedBy]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [CK_MembersOfParliament_Date] CHECK ([FromDate]<[ToDate])
);

