CREATE TABLE [dbo].[UserMP]
(
	[ID] INT IDENTITY(1,1) NOT NULL,
	[MPID] INT NOT NULL,
	[CreatedBy] INT NOT NULL,
	[CreatedDate] DATETIME NOT NULL
	CONSTRAINT PK_UserMP PRIMARY KEY (ID),
	CONSTRAINT FK_UserMP_User FOREIGN KEY (CreatedBy) REFERENCES [dbo].[User](ID)
)
