CREATE TABLE [dbo].[UserMP]
(
	[ID] INT IDENTITY(1,1) NOT NULL,
	[UserID] INT NOT NULL,
	[MPID] INT NOT NULL,
	[CreatedBy] INT NOT NULL,
	[CreatedDate] DATETIME NOT NULL
	CONSTRAINT PK_UserMP PRIMARY KEY (ID),
	CONSTRAINT UK_UserMP_UserID_MPID UNIQUE (UserID, MPID),
	CONSTRAINT FK_UserMP_UserID FOREIGN KEY (UserID) REFERENCES [dbo].[User](ID),
	CONSTRAINT FK_UserMP_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES [dbo].[User](ID)
)
