//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Triad.CabinetOffice.Slipping.Data.EntityFramework.PAWS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public int ID { get; set; }
        public int DivisionNumber { get; set; }
        public System.DateTime DivisionDateTime { get; set; }
        public string Title { get; set; }
        public string GovtLine { get; set; }
        public Nullable<decimal> Ayes { get; set; }
        public Nullable<decimal> Noes { get; set; }
        public bool DeferredDivision { get; set; }
        public int SessionID { get; set; }
        public int WhippingID { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Teller1ForAyes { get; set; }
        public Nullable<int> Teller2ForAyes { get; set; }
        public Nullable<int> Teller1ForNoes { get; set; }
        public Nullable<int> Teller2ForNoes { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int LastChangedBy { get; set; }
        public System.DateTime LastChangedDate { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
