//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Triad.CabinetOffice.Slipping.Data.EntityFramework.PAWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members_of_Parliament
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Forenames { get; set; }
        public string Surname { get; set; }
        public System.DateTime From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public string Email_Address { get; set; }
        public string Mobile { get; set; }
        public string Government_Position { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> Constituency { get; set; }
        public int Party { get; set; }
        public string List_As { get; set; }
        public string Member_Id { get; set; }
        public string Dods_Id { get; set; }
        public string Pims_Id { get; set; }
        public string Full_Name { get; set; }
    }
}
