//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Triad.CabinetOffice.Slipping.Data.EntityFramework.Slipping
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SlippingEntities : DbContext
    {
        public SlippingEntities()
            : base("name=SlippingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbsenceRequest> AbsenceRequests { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserMP> UserMPs { get; set; }
        public virtual DbSet<AbsenceRequestOppositionMP> AbsenceRequestOppositionMPs { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
    }
}
